### ISSUE TITLE
How to use this with VSCode intelephense?

### ISSUE THREAD

**Issue by RS-DU34** [php-stubs/woocommerce-stubs#19] opened 2022-11-10 01:11 UTC
Is there a way to activate this without composer, for example?
Thanks!

**Comment by szepeviktor** [comment] 2022-11-10 06:37
Hello @lflfm! Thank you for raising this issue.

I do not use an IDE.
But Intelephense repo has an issue about this.

Duplicate of #17

**Closed as completed by szepeviktor** 2022-11-10 06:37 UTC
